### ISSUE TITLE
Expected renderToDOM

### ISSUE THREAD

**Issue by captDaylight** [elite174/storybook-solid-js#2]
Thanks for making this example!

I'm getting this error when I run it with a trivial component and a very similar vite setup.
```
Error: Expected your framework's preset to export a `renderToDOM` field.

Perhaps it needs to be upgraded for Storybook 6.4?
```

I have the same version of storybook from your package, `7.0.0-beta` so not sure what the 6.4 message is about.

**Comment by elite174** [comment]
@captDaylight could you provide steps to reproduce this?

**Comment by captDaylight** [comment]
I can provide some more context after messing around with it. I have my package in a Nx monorepo setup and when I put your code into my workspace it doesn't work... but when it's outside of the monorepo it does work just fine.

**Comment by elite174** [comment]
It seems like you have stale symlinks in your monorepo. I'd suggest you to clear the cache and reinstall all deps. BTW it might be helpful to initialize the storybook with `npx storybook init` and etc.

**Comment by captDaylight** [comment]
Yup clearing cache and reinstalling did it, appreciate all the help @elite174 !
