### ISSUE TITLE
note about newer version not working

### ISSUE THREAD

**Issue by unional** [elite174/storybook-solid-js#3]
Thanks for creating this example. Works great.

Just want to share that if I upgrade the versions to 7.0.0-beta.55,
I got:

```
ReferenceError: process is not defined
    at node_modules/util/util.js (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-MEV2Q23E.js?v=2948c77e:1213:5)
    at __require2 (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-HYZYPRER.js?v=2948c77e:15:50)
    at node_modules/assert/build/internal/assert/assertion_error.js (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-MEV2Q23E.js?v=2948c77e:2042:20)
    at __require2 (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-HYZYPRER.js?v=2948c77e:15:50)
    at node_modules/assert/build/assert.js (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-MEV2Q23E.js?v=2948c77e:3359:26)
    at __require2 (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-HYZYPRER.js?v=2948c77e:15:50)
    at http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-MEV2Q23E.js?v=2948c77e:3843:24
    at node_modules/doctrine/lib/utility.js (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-MEV2Q23E.js?v=2948c77e:3844:7)
    at __require2 (http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-HYZYPRER.js?v=2948c77e:15:50)
    at http://localhost:6007/node_modules/.cache/.vite-storybook/deps/chunk-MEV2Q23E.js?v=2948c77e:3855:17
```

It's probably the newer version added the assertion module causing this.

**Comment by elite174** [comment]
what is your node version?

**Comment by elite174** [comment]
Also, how did you update the version?

I did the following steps:

1) Installed all deps with `npm i`
2) Ran `npx storybook upgrade`
2.1) Got these versions of packages
![image](https://user-images.githubusercontent.com/13636224/221815745-c63c4f53-5be2-40c8-a4bf-9b118ffaa054.png)

With these versions everything works well.

My node version is 16.19.0

**Comment by elite174** [comment]
Storybook 7 has not been released yet, so I'd suggest you to wait for the March release. I'll update the repo after release.

**Comment by unional** [comment]
Sure, just dropping a note mentioning it does not work with beta-55.
I upgrade by simply doing `npm up`.

Locally, I can't run `[p]npx storybook upgrade` as I'm using workspace protocol. So I got:

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^
```

**Comment by captDaylight** [comment]
I was getting a similar error but this worked it out for me:

``` js
const { mergeConfig } = require('vite');

module.exports = {
  async viteFinal(config, { configType }) {
    return mergeConfig(config, {
      define: { 'process.env': {} },
    });
  },
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions'
  ],
  framework: {
    name: '@storybook/html-vite',
    options: {}
  },
  docs: {
    autodocs: 'tag'
  }
};

```

**Comment by elite174** [comment]
> Sure, just dropping a note mentioning it does not work with beta-55. I upgrade by simply doing `npm up`.
> 
> Locally, I can't run `[p]npx storybook upgrade` as I'm using workspace protocol. So I got:
> 
> ```
> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "workspace:": workspace:^
> ```

As I understand the only correct way to upgrade storybook is to use the storybook command `upgrade`, because storybook will look to your `package.json` and correctly update all the versions. Also, it might be the case when some storybook versions haven't been tested well yet (because it's only beta).

**Comment by elite174** [comment]
So I suppose the main issue here is how to properly setup storybook in monorepo. Are there any guides on this?

**Comment by unional** [comment]
for `pnpm`, I have to do:

```
pnpm i -g storybook
storybook upgrade
```

`pnpx` doesn't work.

Also, it updates `react-vite` to the alpha version, which is wrong. I need to manually update it back to the beta version.

**Comment by elite174** [comment]
I think that's because `react-vite` is not tagged as `latest`, so the alpha version is the latest version for storybook. Need to wait for the release.

**Comment by elite174** [comment]
@unional 
Updated my repo for the latest storybook! Everything works as expected, check this out :)
