### ISSUE TITLE
Can we use this setup with solid-start/vite?

### ISSUE THREAD

**Issue by ministerofpanic** [elite174/storybook-solid-js#5]
Hey 👋🏻 

Your guide helped get me up and running, thank you.

In the guide, we use `vite-plugin-solid` in vite.config.ts as a plugin, which works.

Now I'm moving over to using `solid-start` so I can join everything up into a working app. To do this, I have to use a different plugin (`solid-start/vite`) - but doing this causes an error. Do you know if it's possible to use solid-start & storybook 7 successfully together?

The error:
```
ERR! TypeError: Cannot read properties of null (reading 'once')
ERR!     at configureServer (file:///Users/mike/Documents/shots-fired/node_modules/solid-start/vite/plugin.js:146:23)
ERR!     at Module.createServer (file:///Users/mike/Documents/shots-fired/node_modules/vite/dist/node/chunks/dep-79892de8.js:62948:30)
ERR!     at Module.start (/Users/mike/Documents/shots-fired/node_modules/@storybook/builder-vite/dist/index.js:160:12552)
ERR!     at async storybookDevServer (/Users/mike/Documents/shots-fired/node_modules/@storybook/core-server/dist/index.js:35:7330)
ERR!     at async buildDevStandalone (/Users/mike/Documents/shots-fired/node_modules/@storybook/core-server/dist/index.js:48:2786)
ERR!     at async withTelemetry (/Users/mike/Documents/shots-fired/node_modules/@storybook/core-server/dist/index.js:35:3620)
ERR!     at async dev (/Users/mike/Documents/shots-fired/node_modules/@storybook/cli/dist/generate.js:430:400)
ERR!     at async Command.<anonymous> (/Users/mike/Documents/shots-fired/node_modules/@storybook/cli/dist/generate.js:432:225)
```

I'm using SB 7.0.18.

**Comment by elite174** [comment]
hi @artdevgame, sorry for late answer.
First thing I'd suggest to you is to use official (community) integration with storybook: https://storybook.js.org/docs/solid/get-started/install/

Another thing that may help is located here: https://discord.com/channels/722131463138705510/1103677541769814046

Some guys had the similar problem, so there's some workaround.
